import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { classNames } from "@/utils/utils";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { SocketProvider } from "@/components/provider/SocketProvider";

const notoSans = Noto_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-noto-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={classNames(notoSans.variable, "font-sans")}>
        <SocketProvider>
          <Header />
          {children}
          <Footer />
        </SocketProvider>
      </body>
    </html>
  );
}
