import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import "./globals.css";
import { classNames } from "@/utils/utils";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const nanum_gothic = Nanum_Gothic({
  weight: ["400", "700", "800"],
  subsets: ["latin"],
  variable: "--font-nanum-gothic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={classNames(nanum_gothic.variable, "font-sans")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
